### ISSUE TITLE
print loan application

### ISSUE THREAD

**Issue by tanviGanesh** [webaccess/SESTA-FMS#129]
https://drive.google.com/drive/folders/1df9Q6klqZr2iMcRNLzhtn2RaIHXQhMCi?ouid=ued44473e1bbf0200 - loan application form

**Comment by minalapte** [comment]
1. print button not working 
fpo admin
csp user
![print button not working](https://user-images.githubusercontent.com/64399966/93171712-3b6d9f00-f747-11ea-84da-465e197983c4.png)
![Image Pasted at 2020-9-15 11-28](https://user-images.githubusercontent.com/64399966/93171731-432d4380-f747-11ea-927a-41266a143883.png)
