### ISSUE TITLE
Active button display when select multiple country to delete

### ISSUE THREAD

**Issue by minalapte** [webaccess/SESTA-FMS#204]
1. Login with Sesta admin
2. Go to Master< Country 
3. Select multiple country to delect
4. Check button
Issue: Active button display when select multiple country to delete
Please refer screen
![Active button display when select multiple country to delete](https://user-images.githubusercontent.com/64399966/91424341-4daa9a80-e877-11ea-8c0c-7eaae6ed6d5b.png)

**Comment by pooja1425** [comment]
There will be no Active button after selecting all records.

**Comment by minalapte** [comment]
Issue has been resolved and tested
Hence closed
![Test_Result_204](https://user-images.githubusercontent.com/64399966/92376866-d996af00-f120-11ea-877b-06687e2fd56c.png)
