### ISSUE TITLE
Cancel button is display instead of reset button in fpo login

### ISSUE THREAD

**Issue by minalapte** [webaccess/SESTA-FMS#205]
1. Login with FPO admin
2. Go to Members
3. Click on add members
4. Check button
Issue: Cancel button is display instead of reset button
Please refer screen

![Cancel button is display instead of reset button in fpo login](https://user-images.githubusercontent.com/64399966/91425518-dbd35080-e878-11ea-9bc2-2b7df80af140.png)

**Comment by pooja1425** [comment]
Not a valid issue.
It should be Cancel only.

**Comment by minalapte** [comment]
Issue has been resolved
Hence closed
PFA
![Test_Result_205](https://user-images.githubusercontent.com/64399966/91730098-23344680-ebc3-11ea-8c88-8220cfb455e8.png)
