### ISSUE TITLE
State added by one fpo admin disply in another fpo admin

### ISSUE THREAD

**Issue by minalapte** [webaccess/SESTA-FMS#209]
1.Login with credential
2.Go to one fpo admin
3.Add state
3.Check added state in another fpo admin login 

Issue: AAdes state display in another fpo admin login
Please refer screenshot
![state added by one fpo admin disply in another fpo admin](https://user-images.githubusercontent.com/64399966/91434847-06c2a200-e883-11ea-8df9-535ecc9bd3eb.png)

**Comment by pooja1425** [comment]
There is no user wise restriction for states/villages/countries.
