### ISSUE TITLE
save button not working on edit loan emi form

### ISSUE THREAD

**Issue by minalapte** [webaccess/SESTA-FMS#221]
1.Login with Sesta admin
2.Go to Loans < Manage Loan Application
3. Select any member and click on emi icon
4. Clcik on edit of any emi to update
5. Enter deatils and click on save

Issue: save button not working on edit loan emi form
Please refer screenshot
![save button not working on edit loan emi form](https://user-images.githubusercontent.com/64399966/91540971-3b913080-e939-11ea-8f0f-cb4995e95c31.png)

**Comment by guptalalita** [comment]
Not replicated
