### ISSUE TITLE
Not allows to save user with duplicate mobile no.

### ISSUE THREAD

**Issue by minalapte** [webaccess/SESTA-FMS#235]
1. Go to sesta admin
2. Go to users< add user
3. Enter duplicate phone no(Already added)
4. Clcik on save

Issue: Not allows to save entry
pfa
![Not allows to save user with duplicate mobile no](https://user-images.githubusercontent.com/64399966/91977242-f6596e00-ed3f-11ea-9497-a396247aed16.png)

**Comment by tanviGanesh** [comment]
@minalapte it should not allow to save duplicate phone number.error should be thrown.

**Comment by minalapte** [comment]
USE mobile no. which already added in member form
