### ISSUE TITLE
Not allows to save entry

### ISSUE THREAD

**Issue by minalapte** [webaccess/SESTA-FMS#288]
1.Go to sesta admin
2.Go to users< add user
3.Enter duplicate phone no(Already added in member form)
4. Click on save
Issue: Not allows to save entry
![duplicate_phone_n0](https://user-images.githubusercontent.com/64399966/92598443-72b2fa80-f2c6-11ea-8daf-86e24b186807.png)

**Comment by tanviGanesh** [comment]
@minalapte can you please retest it. unable to reproduce this scenario
