### ISSUE TITLE
Two message display same time

### ISSUE THREAD

**Issue by minalapte** [webaccess/SESTA-FMS#297]
1. Go to sesta login page
2. Go to forgot password
3. Enter mobile no clcik on send 
4. Enter wrong otp
5. Again click on resend otp
6.Check validation messages

Issue: Two message display same time 
1. OTP Successfully sent
2.Error verifying otp.
![Two message display same time](https://user-images.githubusercontent.com/64399966/92697658-2a98e400-f369-11ea-9d3e-d5fe7b749bb5.png)

**Comment by aplaplikasiapl-prog** [comment]
WhatsApp messenger
